config/routes.rb
Rails.application.routes.draw do
  root 'chats#index'
  devise_for :users
  resources :articles, only: [:index, :show, :new, :create]
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 1 }
  validates :text, presence: true, length: { minimum: 3 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
  after_create_commit { CommentBroadcastJob.perform_later(self) }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  after_create_commit :broadcast_message
  validates :body, presence: true, length: {minimum: 1, maximum: 1000}

  private

  def broadcast_message
    MessageBroadcastJob.perform_later(self)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :messages, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :commments, dependent: :destroy

  def name
    email.split('@')[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.includes(:comments).find_by(id: params[:id])
  end

  def new
    article = Article.new
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def index
    @messages = Message.order(created_at: :asc)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/index.html.erb
<h1 class='text-center'>Articles</h1>
<%= link_to 'New article', new_article_path, class: 'btn btn-outline-info mb-3' %>
 
<% @articles.each do |article| %>
  <div class='card mb-3'>
    <div class='row'>
    <div class='col-md-3'>
      <%= image_tag('photo.png', class: 'card-img-top') %>
    </div>
    <div class='col-md-9'>
      <h4 class='card-header text-info'><%= article.title %></h4>
      <p class='card-body text-truncate'><%= article.text %></p>
      <%= link_to 'Read more >>', article_path(article), class: 'btn btn-light' %>
    </div>
    </div>
  </div>
<% end %>

app/views/articles/new.html.erb
<h3 class='text-center text-info mt-3'>Create article</h3>
<div class='col-md-6 mx-auto'>
  <%= form_for :article, url: articles_path do |form| %>
    <div class='form-group'>
      <%= form.label :title %><br>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class='form-group'>
      <%= form.label :text %><br>
      <%= form.text_area :text, rows: 5, class: 'form-control' %>
    </div>

      <%= form.submit 'Create', class: 'btn btn-outline-info mb-2' %>
  <% end %>

  <%= link_to 'Back', articles_path, class: 'btn btn-light' %>
</div>

app/views/articles/show.html.erb
<h3 class='text-center text-info mt-3'><%= @article.title %></h3>

<div class='row'>
  <div class='col-md-8'>
    <p><%= @article.text %></p>
  </div>
  <div class='col-md-4'>
    <%= image_tag('photo.png', class: 'card-img-top') %>
  </div>
</div>

<%= link_to 'Back', articles_path, class: 'btn btn-light' %>
<hr/> 

<h4>Comments:</h4>

<div id='comments' data-article-id="<=% @article.id %>">
  <%= render @article.comments %>
</div>

<%= form_with url: '#', html: {id: 'new-comment'} do |f| %>
  <%= f.text_area :body, id: 'comment-body', placeholder: 'Write a comment', rows: 3, class: 'form-control input-field' %>
  <%= f.submit 'Comment', class: 'btn btn-outline-info mt-2' %>
<% end %>

app/views/chats/index.html.erb
<div class='col-md-8 mx-auto'>
  <h1 class='text-center'>Chat</h1>
  <div id='messages'>
    <%= render @messages %>
  </div>

  <%= form_with url: '#', html: {id: 'new-message'} do |f| %>
    <%= f.text_area :body, id: 'message-body', autofocus: true, placeholder: 'Write a message', rows: 3, class: 'form-control' %>
    <br>
    <%= f.submit 'Send', class: 'btn btn-outline-info' %>
  <% end %>
</div>

app/views/comments/_comment.html.erb
<div class='card border-info mb-3'>
  <div class='card-body'>
    <div class='row'>
      <div class='col-md-1'>
        <%= image_tag('person-icon.png', class: 'img-fluid') %>
      </div>
      <div class='col-md-11'>
        <div class='row'>
          <div class='col-md-6'>
            <strong><%= comment.user.name %></strong>:
          </div>
          <div class='col-md-6 text-right'>
            <small>at <%= l comment.created_at, format: :short %></small>
          </div>
        </div>
        <%= comment.body %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <nav class='navbar navbar-expand-sm bg-light navbar-light'>
        <ul class='navbar-nav'>
          <li class='nav-item'><%= link_to 'Articles', articles_path, class: 'nav-link' %></li>
          <li class='nav-item'><%= link_to 'Chat', root_path, class: 'nav-link' %></li>
        </ul>
        <ul class='navbar-nav ml-auto'>
          <% if signed_in? %>
            <li class='nav-item nav-link'>Signed in as: <%= current_user.email %></li>
            <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
          <% else %>
            <li class='nav-item'><%= link_to 'Log in', new_user_session_path, class: 'nav-link' %></li>
            <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
          <% end %>
        </ul>
      </nav>

      <div id="flash">
        <% flash.each do |key, value| %>
          <%= tag.div value, class: 'alert alert-info' %>
        <% end %>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class='card border-info mb-3'>
<!-- <div class="card border-#{current_user.id == message.user_id ? 'info' : 'success'} mb-3"> -->
  <div class='card-body'>
    <div class='row'>
      <div class='col-md-2'>
        <%= image_tag('person-icon.png', class: 'img-fluid') %>
      </div>
      <div class='col-md-10'>
        <div class='row'>
          <div class='col-md-6'>
            <strong><%= message.user.name %></strong>:
          </div>
          <div class='col-md-6 text-right'>
            <small>at <%= l message.created_at, format: :short %></small>
          </div>
        </div>
        <%= message.body %>
      </div>
    </div>
  </div>
</div>